identifier: alice_v1
name: Alice Rev1 BOARD
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - ble
  - RGB
  - ieee802154
  - watchdog